baseurl = "https://cottonflex.netlify.app/"
languageCode = "en-us"
title = "CottonFlex"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "CottonFlex"
  defaultImage = "panflet.jpg"
 

  email = "contatocottonflex@gmail.com"
  instagram = "https://www.instagram.com/cottonflexelasticos/"
  whatsapp = "+55 11 94603-2627"
  facebook = ""
  quora = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "CottonFlex"
     link = "https://cottonflex.netlify.app/"
