baseurl = "https://cottonflex.netlify.app/"
languageCode = "en-us"
title = "CottonFlex"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "CottonFlex"
  defaultImage = "cotton_flex.png"

  email = "contatocottonflex@gmail.com"
  instagram = "https://instagram.com"
  whatsapp = "https://www.whatsapp.com/"
  facebook = ""
  quora = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "CottonFlex"
     link = "https://cottonflex.netlify.app/"
